---
# Переменные для подключения к PostgreSQL
db_host: "c-c9qganct6ib929heotcf.rw.mdb.yandexcloud.net"
db_port: "6432"
db_user: "appuser"
db_password: "CYkKBf7GW-yawgx"
db_name: "appdb"

# Docker образ
docker_image: "hermanasoul/devops-app:latest"

redmine_port: 8080
redmine_db_name: redmine
redmine_db_user: redmine
redmine_db_password: "fwAduA4se-QaAqS"